//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jtd_som_360spiff {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class spiff : global::System.Configuration.ApplicationSettingsBase {
        
        private static spiff defaultInstance = ((spiff)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new spiff())));
        
        public static spiff Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select s.* from P21.dbo.SOM_SomShipmentDetail d
join p21.dbo.SOM_SomShipmentSerial s on s.invnbr = d.invnbr and s.invseq = d.invseq and s.itmnbr = d.itmnbr
join p21.dbo.inv_mast i on i.item_id = d.ITMMDL
join p21.dbo.inv_loc l on l.inv_mast_uid = i.inv_mast_uid 
join p21.dbo.vendor v on l.primary_supplier_id = v.vendor_id
where l.location_id = '10' and (v.vendor_id = '10008' or v.vendor_id = '10009') and i.serialized = 'Y'
")]
        public string SqlQuery {
            get {
                return ((string)(this["SqlQuery"]));
            }
            set {
                this["SqlQuery"] = value;
            }
        }
    }
}
