//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jtd_som_360spiff.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT DISTINCT
	ih.customer_id AS 'CustNum', 
	c.customer_name AS 'CustName',
	ih.ship_date AS 'ShipDate', 
	dls.serial_number AS 'SerialNum',
	im.item_id AS ModelNum
FROM invoice_hdr ih
	INNER JOIN invoice_line il ON ih.invoice_no = il.invoice_no
	INNER JOIN customer c on ih.customer_id = c.customer_id
	INNER JOIN inv_mast im ON il.inv_mast_uid = im.inv_mast_uid
	INNER JOIN document_line_serial dls ON dls.document_no = ih.order_no AND dls.line_no = il.oe_line_number
	INNER JOIN inv_loc l ON l.inv_mast_uid = im.inv_mast_uid AND l.location_id = '10'
	INNER JOIN Supplier s on l.primary_supplier_id = s.supplier_id
WHERE CONVERT(date, ih.invoice_date) = @INVDATE 
  AND l.location_id = '10' and (s.supplier_id = '10008' or s.supplier_id = '10009') and im.serialized = 'Y'
  and ih.customer_id not in ('10080','10081','10082','10083','10086','10087','10091','10092','10093','10094','10095','10096','10101','10102','10103','10104','11652')

")]
        public string SqlQuery {
            get {
                return ((string)(this["SqlQuery"]));
            }
            set {
                this["SqlQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvoiceDate {
            get {
                return ((string)(this["InvoiceDate"]));
            }
            set {
                this["InvoiceDate"] = value;
            }
        }
    }
}
