//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jtd_som_360spiff.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select c.customer_id AS CustNum, c.customer_name AS CustName, d.SHPMTDATE AS ShipDate, s.SRLNBR AS SerialNum, d.ITMMDL AS ModelNum from P21.dbo.SOM_SomShipmentDetail d
join p21.dbo.SOM_SomShipmentSerial s on s.invnbr = d.invnbr and s.invseq = d.invseq and s.itmnbr = d.itmnbr
join p21.dbo.inv_mast i on i.item_id = d.ITMMDL
join p21.dbo.inv_loc l on l.inv_mast_uid = i.inv_mast_uid 
join p21.dbo.vendor v on l.primary_supplier_id = v.vendor_id
join p21.dbo.customer c on c.customer_id = d.PTRCUSID
where l.location_id = '10' and (v.vendor_id = '10008' or v.vendor_id = '10009') and i.serialized = 'Y'
  and c.customer_id not in ('10080','10081','10082','10083','10086','10087','10091','10092','10093','10094','10095','10096','10101','10102','10103','10104','11652')")]
        public string SqlQuery {
            get {
                return ((string)(this["SqlQuery"]));
            }
            set {
                this["SqlQuery"] = value;
            }
        }
    }
}
